name: Rituparna's website
description: let me show you the world where I belong
twitter_username: Rituparna
github username: ritumish
author: rituparna.mish@gmail.com

markdown: kramdown

remote theme: just-the-docs/just-the-docs
